version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          cache-key: "package-lock.json"
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm test
      - persist_to_workspace:
          root: .
          paths:
            - dist

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
